package com.skyblu.configuration

import android.Manifest

val APP_NAME_STRING = "Skyblu"
val ID_STRING = "ID"
val EMAIL_STRING = "Email"
val TITLE_STRING = "Title"
val DROPZONE_STRING = "Dropzone"
val AIRCRAFT_STRING = "Aircraft"
val EQUIPMENT_STRING = "Equipment"
val DESCRIPTION_STRING = "Description"
val EDIT_JUMP_STRING = "Edit Skydive"
val UNKNOWN_USER_STRING = "Unknown User"
val SPEEDS_STRING = "Speeds"
val MAX_VERTICAL_SPEED_STRING = "Maximum Vertical Speed"
val AVERAGE_GROUND_SPEED_STRING = "Average Ground Speed"
val AVERAGE_VERTICAL_SPEED_STRING = "Average Vertical Speed"
val MAX_GROUND_SPEED_STRING = "Max Ground Speed"
val MPS_UNIT_STRING = "m/s"
val M_UNIT_STRING = "m"
val FT_UNIT_STRING = "ft"
val TWO_DP_FORMAT_STRING = "%.2f"
val DP_FORMAT_STRING = "%.1f"
val EXIT_ALTITUDE_STRING = "Exit Altitude"
val OPENING_ALTITUDE_STRING = "Opening Altitude"
val DISTANCES_STRING = "Distances"
val ALTITUDES_STRING = "Altitudes"
val JUMP_DETAILS_STRING = "Skydive Details"
val FREEFALL_STRING = "Freefall"
val CANOPY_STRING = "Canopy"
val UNKNOWN_STRING = "Unknown"
val START_TRACKING_STRING = "Start Tracking"
val STOP_TRACKING_STRING = "Stop Tracking"
val PASSWORD_STRING = "Password"
val CONFIRM_PASSWORD_STRING = "Confirm Password"
val WELCOME_MESSAGE_STRING = "Welcome to $APP_NAME_STRING"
val LOGIN_TO_APP_STRING = "Login to $APP_NAME_STRING"
val DONT_HAVE_ACCOUNT_STRING = "Don't have an account? Create Account"
val ACCOUNT_SETTINGS_STRING = "Account Settings"
val IMAGE_REFERENCE_STRING = "image/*"
val USERNAME_STRING = "Username"
val BIO_STRING = "Bio String"
val TRACKING_SETTINGS_STRING = "Tracking Settings"
val PROFILE_STRING = "Profile"
val HOME_STRING = "Home"
val VERTICAL_DISTANCE_TRAVELLED_STRING = "Vertical Distance Travelled"
val GROUND_DISTANCE_TRAVELLED_STRING = "ground Distance Travelled"
val LOADING_STRING = "Loading"
val PERMISSIONS = Manifest.permission.ACCESS_FINE_LOCATION
val JUMPS_COLLECTION = "skydives"
val USERS_COLLECTION = "users"
val DATAPOINTS_COLLECTION = "datapoints"
val JUMP_PAGE_SIZE = 5

